version: '3'
services:
  api:
    image: temp-api
    build: api/
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - API_PORT=3000
    ports:
      - "3000:3000"
  web:
    image: temp-web
    build: web/
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - /app/.angular
      - ./web:/app
    environment:
      - WEB_PORT=4200
  database:
    image: temp-db
    build: database-main/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin_123
    volumes:
    - db-data:/var/lib/mysql
volumes:
  db-data:
